language: scala

jdk:
  - openjdk8
  - oraclejdk8

script:
  - ./sbt clean undeclaredCompileDependenciesTest unusedCompileDependenciesTest coverage test coverageReport &&
    ./sbt coverageAggregate

after_success:
  - ./sbt coveralls